version: "3"
services:
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pankaj
      MYSQL_ROOT_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro

  app:
    build: ./app
    volumes:
      - ./app:/app
    ports:
      - "8080:8080"